name: CI Release Helm Chart

on:
  release:
    types: [published]

env:
  REPO_NAME: magda-csv-connector

jobs:
  release-helm-chart:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - name: helm-check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./deploy/magda-csv-connector
          CHART_VALUES: ./deploy/test-deploy.yaml

      - name: Login to GitHub Package Repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: docker login docker.pkg.github.com -u magdabot -p ${GH_TOKEN}

      - name: Build Docker Image & Push to Github Registry
        run: yarn docker-build-prod --repository=docker.pkg.github.com/magda-io/${REPO_NAME} --name=${REPO_NAME}

      - name: Login to Docker Hub
        env:
          DH_TOKEN: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: docker login -u magdabot -p ${DH_TOKEN}

      - name: Re-tag & Push Docker Image to Docker Hub
        run: yarn retag-and-push --fromPrefix=docker.pkg.github.com/magda-io/${REPO_NAME}/ --fromName=${REPO_NAME}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v2.16.1

      - name: Setup AWS CLi Tools
        uses: chrislennon/action-aws-cli@v1.1

      - name: Release Helm Chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_ACCESS_TOKEN }}"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Sync with existing charts repo in s3..."
          mkdir -p chart-repo
          aws s3 sync s3://magda-charts/ chart-repo
          helm package ./deploy/${REPO_NAME} -d chart-repo --save=false
          helm repo index chart-repo
          echo "Releasing charts to s3..."
          aws s3 sync chart-repo s3://magda-charts/ --acl public-read
